version: '3.9'
services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - WDS_SOCKET_PORT=0
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'